# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# adding tag 'forcebuild' tag 
trigger:
- master
- msz/add-login-again

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Debug'
    
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: '**/servis20pot.tests.unit.csproj'
    arguments: --configuration $(buildConfiguration)


- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
