// <auto-generated />
using System;
using FunkyCode.Blog.Inf.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunkyCode.Blog.Inf.EntityFramework.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200328174627_FixEnum")]
    partial class FixEnum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FunkyCode.Blog.Domain.Entites.BlogPost", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Header");

                    b.Property<DateTime>("PublishingDate");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("FunkyCode.Blog.Domain.Entites.BlogPostImage", b =>
                {
                    b.Property<string>("BlogPostId");

                    b.Property<string>("Id");

                    b.Property<byte[]>("Data");

                    b.HasKey("BlogPostId", "Id");

                    b.ToTable("BlogPostImages");
                });

            modelBuilder.Entity("FunkyCode.Blog.Domain.Entites.BlogPostImage", b =>
                {
                    b.HasOne("FunkyCode.Blog.Domain.Entites.BlogPost", "BlogPost")
                        .WithMany("Images")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
